# Generated by Django 4.0.4 on 2022-10-30 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_topic_chatrooms_host_chatrooms_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRooms',
            new_name='ChatRoom',
        ),
    ]
