# Generated by Django 4.0.4 on 2022-11-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
